<?php

return [
    'default' => env('SMSAPI_DRIVER', 'smsir'),

    'drivers' => [
        'smsir' => [
            'api_key' => env('SMSAPI_API_KEY'),
            'line_number' => env('SMSAPI_LINE_NUMBER'),
            'base_url' => env('SMSAPI_BASE_URL', 'https://api.sms.ir/v1'),
            'timeout' => env('SMSAPI_TIMEOUT', 30),
        ],
        'kavenegar' => [
            'api_key' => env('KAVENEGAR_API_KEY'),
            'line_number' => env('KAVENEGAR_LINE_NUMBER'),
            'base_url' => env('KAVENEGAR_BASE_URL', 'https://api.kavenegar.com/v1'),
            'timeout' => env('KAVENEGAR_TIMEOUT', 30),
        ],
        'ghasedak' => [
            'api_key' => env('GHASEDAK_API_KEY'),
            'line_number' => env('GHASEDAK_LINE_NUMBER'),
            'base_url' => env('GHASEDAK_BASE_URL', 'https://api.ghasedak.me/v2'),
            'timeout' => env('GHASEDAK_TIMEOUT', 30),
        ],
        'farazsms' => [
            'api_key' => env('FARAZSMS_API_KEY'),
            'line_number' => env('FARAZSMS_LINE_NUMBER'),
            'base_url' => env('FARAZSMS_BASE_URL', 'https://api2.ippanel.com/api/v1'),
            'timeout' => env('FARAZSMS_TIMEOUT', 30),
        ],
        'ippanel' => [
            'api_key' => env('IPPANEL_API_KEY'),
            'line_number' => env('IPPANEL_LINE_NUMBER'),
            'base_url' => env('IPPANEL_BASE_URL', 'https://api2.ippanel.com/api/v1'),
            'timeout' => env('IPPANEL_TIMEOUT', 30),
        ],
        'magfa' => [
            'username' => env('MAGFA_USERNAME'),
            'password' => env('MAGFA_PASSWORD'),
            'domain' => env('MAGFA_DOMAIN', 'magfa'),
            'line_number' => env('MAGFA_LINE_NUMBER'),
            'base_url' => env('MAGFA_BASE_URL', 'https://sms.magfa.com/api/http/sms/v2'),
            'timeout' => env('MAGFA_TIMEOUT', 30),
        ],
        'niksms' => [
            'username' => env('NIKSMS_USERNAME'),
            'password' => env('NIKSMS_PASSWORD'),
            'line_number' => env('NIKSMS_LINE_NUMBER'),
            'base_url' => env('NIKSMS_BASE_URL', 'https://niksms.com/api/v2'),
            'timeout' => env('NIKSMS_TIMEOUT', 30),
        ],
        'mediana' => [
            'api_key' => env('MEDIANA_API_KEY'),
            'line_number' => env('MEDIANA_LINE_NUMBER'),
            'base_url' => env('MEDIANA_BASE_URL', 'https://api.mediana.ir'),
            'timeout' => env('MEDIANA_TIMEOUT', 30),
        ],
        'limosms' => [
            'api_key' => env('LIMOSMS_API_KEY'),
            'line_number' => env('LIMOSMS_LINE_NUMBER'),
            'base_url' => env('LIMOSMS_BASE_URL', 'https://api.limosms.com'),
            'timeout' => env('LIMOSMS_TIMEOUT', 30),
        ],
        'melipayamak' => [
            'username' => env('MELIPAYAMAK_USERNAME'),
            'password' => env('MELIPAYAMAK_PASSWORD'),
            'line_number' => env('MELIPAYAMAK_LINE_NUMBER'),
            'base_url' => env('MELIPAYAMAK_BASE_URL', 'https://rest.payamak-panel.com/api'),
            'timeout' => env('MELIPAYAMAK_TIMEOUT', 30),
        ],
        'farapayamak' => [
            'username' => env('FARAPAYAMAK_USERNAME'),
            'password' => env('FARAPAYAMAK_PASSWORD'),
            'line_number' => env('FARAPAYAMAK_LINE_NUMBER'),
            'base_url' => env('FARAPAYAMAK_BASE_URL', 'https://rest.payamak-panel.com/api'),
            'timeout' => env('FARAPAYAMAK_TIMEOUT', 30),
        ],
        'payamito' => [
            'username' => env('PAYAMITO_USERNAME'),
            'password' => env('PAYAMITO_PASSWORD'),
            'line_number' => env('PAYAMITO_LINE_NUMBER'),
            'base_url' => env('PAYAMITO_BASE_URL', 'https://rest.payamak-panel.com/api'),
            'timeout' => env('PAYAMITO_TIMEOUT', 30),
        ],
        'payamaknovin' => [
            'username' => env('PAYAMAKNOVIN_USERNAME'),
            'password' => env('PAYAMAKNOVIN_PASSWORD'),
            'line_number' => env('PAYAMAKNOVIN_LINE_NUMBER'),
            'base_url' => env('PAYAMAKNOVIN_BASE_URL', 'https://rest.payamak-panel.com/api'),
            'timeout' => env('PAYAMAKNOVIN_TIMEOUT', 30),
        ],
        'bahmanpayam' => [
            'username' => env('BAHMANPAYAM_USERNAME'),
            'password' => env('BAHMANPAYAM_PASSWORD'),
            'line_number' => env('BAHMANPAYAM_LINE_NUMBER'),
            'base_url' => env('BAHMANPAYAM_BASE_URL', 'https://rest.payamak-panel.com/api'),
            'timeout' => env('BAHMANPAYAM_TIMEOUT', 30),
        ],
        'amoot' => [
            'username' => env('AMOOT_USERNAME'),
            'password' => env('AMOOT_PASSWORD'),
            'line_number' => env('AMOOT_LINE_NUMBER'),
            'base_url' => env('AMOOT_BASE_URL', 'https://rest.payamak-panel.com/api'),
            'timeout' => env('AMOOT_TIMEOUT', 30),
        ],
        'payamresan' => [
            'api_key' => env('PAYAMRESAN_API_KEY'),
            'line_number' => env('PAYAMRESAN_LINE_NUMBER'),
            'base_url' => env('PAYAMRESAN_BASE_URL', 'https://api.sms-webservice.com/api/V3'),
            'timeout' => env('PAYAMRESAN_TIMEOUT', 30),
        ],
        'behinpayam' => [
            'api_key' => env('BEHINPAYAM_API_KEY'),
            'line_number' => env('BEHINPAYAM_LINE_NUMBER'),
            'base_url' => env('BEHINPAYAM_BASE_URL', 'https://api.sms-webservice.com/api/V3'),
            'timeout' => env('BEHINPAYAM_TIMEOUT', 30),
        ],
        'rastinsms' => [
            'api_key' => env('RASTINSMS_API_KEY'),
            'line_number' => env('RASTINSMS_LINE_NUMBER'),
            'base_url' => env('RASTINSMS_BASE_URL', 'https://api.sms-webservice.com/api/V3'),
            'timeout' => env('RASTINSMS_TIMEOUT', 30),
        ],
        'avanak' => [
            'api_token' => env('AVANAK_API_TOKEN'),
            'otp_length' => env('AVANAK_OTP_LENGTH', 5),
            'server_id' => env('AVANAK_SERVER_ID', 0),
            'base_url' => env('AVANAK_BASE_URL', 'https://portal.avanak.ir/rest'),
            'timeout' => env('AVANAK_TIMEOUT', 30),
        ],
        'telegram' => [
            'channel' => 'telegram',
            'bot_token' => env('TELEGRAM_BOT_TOKEN'),
            'timeout' => env('TELEGRAM_TIMEOUT', 30),
        ],
        'whatsapp' => [
            'channel' => 'whatsapp',
            'access_token' => env('WHATSAPP_ACCESS_TOKEN'),
            'phone_number_id' => env('WHATSAPP_PHONE_NUMBER_ID'),
            'api_version' => env('WHATSAPP_API_VERSION', 'v21.0'),
            'base_url' => env('WHATSAPP_BASE_URL', 'https://graph.facebook.com'),
            'timeout' => env('WHATSAPP_TIMEOUT', 30),
        ],
        'bale' => [
            'channel' => 'bale',
            'bot_token' => env('BALE_BOT_TOKEN'),
            'base_url' => env('BALE_BASE_URL', 'https://tapi.bale.ai'),
            'timeout' => env('BALE_TIMEOUT', 30),
        ],
        'eitaa' => [
            'channel' => 'eitaa',
            'token' => env('EITAA_TOKEN'),
            'base_url' => env('EITAA_BASE_URL', 'https://eitaayar.ir'),
            'timeout' => env('EITAA_TIMEOUT', 30),
        ],
        'rubika' => [
            'channel' => 'rubika',
            'bot_token' => env('RUBIKA_BOT_TOKEN'),
            'base_url' => env('RUBIKA_BASE_URL', 'https://botapi.rubika.ir/v3'),
            'timeout' => env('RUBIKA_TIMEOUT', 30),
        ],
        'gap' => [
            'channel' => 'gap',
            'token' => env('GAP_BOT_TOKEN'),
            'base_url' => env('GAP_BASE_URL', 'https://api.gap.im'),
            'timeout' => env('GAP_TIMEOUT', 30),
        ],
        'igap' => [
            'channel' => 'igap',
            'bot_token' => env('IGAP_BOT_TOKEN'),
            'base_url' => env('IGAP_BOT_BASE_URL', 'https://bot.igap.net'),
            'timeout' => env('IGAP_TIMEOUT', 30),
        ],
        'messenger' => [
            'channel' => 'messenger',
            'page_access_token' => env('MESSENGER_PAGE_ACCESS_TOKEN'),
            'page_id' => env('MESSENGER_PAGE_ID', 'me'),
            'api_version' => env('MESSENGER_API_VERSION', 'v21.0'),
            'base_url' => env('MESSENGER_BASE_URL', 'https://graph.facebook.com'),
            'timeout' => env('MESSENGER_TIMEOUT', 30),
        ],
        'viber' => [
            'channel' => 'viber',
            'auth_token' => env('VIBER_AUTH_TOKEN'),
            'sender_name' => env('VIBER_SENDER_NAME', 'Bot'),
            'base_url' => env('VIBER_BASE_URL', 'https://chatapi.viber.com/pa'),
            'timeout' => env('VIBER_TIMEOUT', 30),
        ],
        'line' => [
            'channel' => 'line',
            'channel_access_token' => env('LINE_CHANNEL_ACCESS_TOKEN'),
            'base_url' => env('LINE_BASE_URL', 'https://api.line.me/v2/bot'),
            'timeout' => env('LINE_TIMEOUT', 30),
        ],
        'discord' => [
            'channel' => 'discord',
            'bot_token' => env('DISCORD_BOT_TOKEN'),
            'api_version' => env('DISCORD_API_VERSION', 'v10'),
            'base_url' => env('DISCORD_BASE_URL', 'https://discord.com/api'),
            'timeout' => env('DISCORD_TIMEOUT', 30),
        ],
        'slack' => [
            'channel' => 'slack',
            'bot_token' => env('SLACK_BOT_TOKEN'),
            'base_url' => env('SLACK_BASE_URL', 'https://slack.com/api'),
            'timeout' => env('SLACK_TIMEOUT', 30),
        ],
    ],
];
